"""Criação inicial de tabelas (Usuários, Módulos, ADO, Policies)

Revision ID: af5ddafbf8d6
Revises: 'None'
Create Date: 2025-11-17 05:19:31.812007+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af5ddafbf8d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('policy_rule', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('applies_to', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_applies_to'), 'policies', ['applies_to'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_table('system_modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.Column('grid_column_span', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_modules_id'), 'system_modules', ['id'], unique=False)
    op.create_index(op.f('ix_system_modules_name'), 'system_modules', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('microsoft_id', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('entra_refresh_token', sa.String(), nullable=True),
    sa.Column('entra_refresh_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_microsoft_id'), 'users', ['microsoft_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_ado_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_url', name='_user_org_uc')
    )
    op.create_index(op.f('ix_user_ado_connections_id'), 'user_ado_connections', ['id'], unique=False)
    op.create_table('user_configs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_configs_user_id'), 'user_configs', ['user_id'], unique=False)
    op.create_table('user_module_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['system_modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_module_preferences_id'), 'user_module_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_module_preferences_module_id'), 'user_module_preferences', ['module_id'], unique=False)
    op.create_index(op.f('ix_user_module_preferences_user_id'), 'user_module_preferences', ['user_id'], unique=False)
    op.create_table('ado_project_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['user_ado_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ado_project_configs_id'), 'ado_project_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ado_project_configs_id'), table_name='ado_project_configs')
    op.drop_table('ado_project_configs')
    op.drop_index(op.f('ix_user_module_preferences_user_id'), table_name='user_module_preferences')
    op.drop_index(op.f('ix_user_module_preferences_module_id'), table_name='user_module_preferences')
    op.drop_index(op.f('ix_user_module_preferences_id'), table_name='user_module_preferences')
    op.drop_table('user_module_preferences')
    op.drop_index(op.f('ix_user_configs_user_id'), table_name='user_configs')
    op.drop_table('user_configs')
    op.drop_index(op.f('ix_user_ado_connections_id'), table_name='user_ado_connections')
    op.drop_table('user_ado_connections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_microsoft_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_modules_name'), table_name='system_modules')
    op.drop_index(op.f('ix_system_modules_id'), table_name='system_modules')
    op.drop_table('system_modules')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_applies_to'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###