# config/nginx.conf
server {
    listen 80;
    server_name localhost;

    # O root deve apontar para onde o volume do build do React está mapeado
    root /usr/share/nginx/html;

    # Permite acesso ao index.html
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Evita problemas de CORS ou proxy (embora para o frontend não seja crítico, é boa prática)
    # config/nginx.conf (Substituir o bloco location /api/)

    # Rota de proxy para o Backend FastAPI
    location /api/ {
        # O destino é o nome do serviço Docker (backend) na porta 8000
        proxy_pass http://backend:8000/; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        
        # Opcional: Remove o /api/ do caminho antes de enviar ao FastAPI
        rewrite ^/api/(.*)$ /$1 break; 
    }
}